// Downloads and self-hosts the site's typefaces, and writes src/fonts.css.
//
// Aeonik is the intended display face. It is a COMMERCIAL font from CoType Foundry and
// cannot be downloaded here — it has to be licensed and the woff2 files dropped into
// public/fonts/ as aeonik-{300,400,500,600}.woff2. src/fonts.css already declares the
// @font-face rules for them, so the moment those files exist the site picks Aeonik up
// with no code change.
//
// Until then the stack falls through to Switzer: a free-for-commercial-use neo-grotesque
// from Fontshare with very similar proportions, self-hosted the same way. Swapping is a
// one-line change in src/tokens.css.
//
// Run with: npm run fonts
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "public/fonts");
mkdirSync(OUT, { recursive: true });

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

let css = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted, latin subsets only, so no third-party request sits on the critical path.

   AEONIK is the intended display face and is declared first. It is licensed software:
   drop the licensed woff2 files into public/fonts/ with these exact names and it takes
   over automatically —
       aeonik-300.woff2  aeonik-400.woff2  aeonik-500.woff2  aeonik-600.woff2
   Until those files exist the browser skips these rules and uses the next family in the
   stack (see --font-display in src/tokens.css). */\n`;

// ── Aeonik: declared but not shipped. A missing src is skipped silently by the browser.
for (const w of [300, 400, 500, 600]) {
  css += `
@font-face {
  font-family: 'Aeonik';
  font-style: normal;
  font-weight: ${w};
  font-display: swap;
  src: url('/fonts/aeonik-${w}.woff2') format('woff2');
}\n`;
}
const haveAeonik = [300, 400, 500, 600].every((w) => existsSync(resolve(OUT, `aeonik-${w}.woff2`)));
console.log(haveAeonik ? "Aeonik: licensed files found" : "Aeonik: declared, files not present (add them to public/fonts/)");

// ── Switzer (Fontshare, free for commercial use) — the stand-in until Aeonik lands.
// ── IBM Plex Mono (Google) — the mono face, unchanged.
const SOURCES = [
  {
    name: "Switzer",
    file: "switzer",
    url: "https://api.fontshare.com/v2/css?f[]=switzer@300,400,500,600&display=swap",
  },
  {
    name: "IBM Plex Mono",
    file: "plex-mono",
    url: "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap",
  },
];

const preload = [];
for (const src of SOURCES) {
  const sheet = await fetch(src.url, { headers: { "User-Agent": UA } }).then((r) => r.text());
  // Fontshare emits one @font-face per weight with no subset comments; Google splits by
  // subset. Handle both by walking each @font-face block.
  const blocks = sheet.split("@font-face").slice(1);
  const seen = new Set();
  for (const raw of blocks) {
    const weight = (raw.match(/font-weight:\s*(\d+)/) || [])[1];
    // Fontshare uses protocol-relative URLs; Google uses absolute https.
    let url = (raw.match(/url\((?:"|')?((?:https:)?\/\/[^)"']+\.woff2)/) || [])[1];
    if (url && url.startsWith("//")) url = "https:" + url;
    const range = (raw.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!weight || !url) continue;
    // Google: keep latin only. Fontshare ships one file per weight already.
    if (range && !/U\+0000-00FF/.test(range) && !/U\+0100-02AF/.test(range)) continue;
    const key = `${src.file}-${weight}`;
    if (seen.has(key)) continue;
    seen.add(key);

    const name = `${key}.woff2`;
    const buf = Buffer.from(await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.arrayBuffer()));
    writeFileSync(resolve(OUT, name), buf);
    css += `
@font-face {
  font-family: '${src.name}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/${name}') format('woff2');${range ? `\n  unicode-range: ${range};` : ""}
}\n`;
    if (weight === "400" || (src.file === "switzer" && weight === "600")) preload.push(`/fonts/${name}`);
    console.log(`  ${name} (${(buf.length / 1024).toFixed(1)} KB)`);
  }
}

writeFileSync(resolve(ROOT, "src/fonts.css"), css, "utf8");
writeFileSync(resolve(ROOT, "src/fonts-preload.json"), JSON.stringify(preload, null, 2), "utf8");
console.log(`\nfonts: wrote src/fonts.css and ${preload.length} preload hints`);
