// Downloads the latin subsets of the two site faces and writes a local @font-face
// stylesheet, so the site stops depending on fonts.googleapis.com.
//
// The CDN link was a render-blocking stylesheet on a third-party origin: two extra
// connections (DNS + TLS) before any text could paint, on the critical path. Spec F7
// asks for fonts to be subset and preloaded — you cannot preload a file whose URL you
// only learn after fetching someone else's CSS.
//
// Run once with `npm run fonts`. The output is committed; this is not part of the build.
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "public/fonts");
mkdirSync(OUT, { recursive: true });

// A modern desktop UA, so Google serves woff2 rather than a legacy format.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  { css: "Inter:wght@300;400;500;600", family: "Inter", file: "inter" },
  { css: "IBM+Plex+Mono:wght@400;500", family: "IBM Plex Mono", file: "plex-mono" },
];

// Only latin and latin-ext. The site is English; shipping Cyrillic, Greek and
// Vietnamese would triple the download for glyphs nothing renders.
const WANTED = new Set(["latin", "latin-ext"]);

let out = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Latin subsets only, self-hosted so no third-party request sits on the critical path. */\n`;
const preload = [];

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());

  // Google emits a comment naming each subset before its @font-face block.
  const blocks = css.split("/*").slice(1);
  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf("*/")).trim();
    if (!WANTED.has(subset)) continue;

    const weight = (raw.match(/font-weight:\s*(\d+)/) || [])[1];
    const src = (raw.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    const range = (raw.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!weight || !src) continue;

    const name = `${fam.file}-${weight}-${subset}.woff2`;
    const buf = Buffer.from(await fetch(src, { headers: { "User-Agent": UA } }).then((r) => r.arrayBuffer()));
    writeFileSync(resolve(OUT, name), buf);

    out += `\n@font-face {
  font-family: '${fam.family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/${name}') format('woff2');
  unicode-range: ${range};
}\n`;

    // Only the regular latin weights are needed for first paint; the rest can wait.
    if (subset === "latin" && (weight === "400" || (fam.file === "inter" && weight === "600"))) {
      preload.push(`/fonts/${name}`);
    }
    console.log(`  ${name} (${(buf.length / 1024).toFixed(1)} KB)`);
  }
}

writeFileSync(resolve(ROOT, "src/fonts.css"), out, "utf8");
writeFileSync(resolve(ROOT, "src/fonts-preload.json"), JSON.stringify(preload, null, 2), "utf8");
console.log(`\nfonts: wrote src/fonts.css and ${preload.length} preload hints`);
