// Every page on the site, in one place. The .html entry files are GENERATED from this
// manifest by scripts/gen-pages.mjs — do not hand-edit the .html files, edit here.
//
//   kind "page"  → content page: mounts src/pages/<dataPage>.svelte via src/page.js
//   kind "model" → standalone 3D demo. Either mounts src/<component>.svelte,
//                   or loads src/<entry> directly into a #scene container.
//   kind "home"  → the homepage hero
//
// title/description are the SEO metadata from the SEO Implementation Strategy v1.0.
//
// index:false keeps a route out of sitemap.xml and marks it noindex. Content pages are
// indexable by default; models are always noindex. indexNote records why, so a later
// owner decision reverses exactly one line. See IMPLEMENTATION_PLAN.md.

export const PAGES = [
  { slug: "404", kind: "page", index: false, indexNote: "utility — must return HTTP 404 and stay out of the index (G11)", title: "Page Not Found | IICL", description: "This page isn't live yet — we're working on it.", dataPage: "not-found", theme: "#060606" },
  { slug: "careers", kind: "page", title: "Careers at IICL | Join Our AI Team", description: "Open roles across AI engineering, voice AI, full-stack development, QA, sales and delivery at IICL, in Hyderabad, Raleigh and remote.", dataPage: "careers", theme: "#ffffff" },
  { slug: "story", kind: "page", index: false, indexNote: "brand experience, not a commercial destination", title: "The Crossing | How IICL Builds With AI", description: "A scroll-driven story: an intelligent system studies a gap, fails at its first bridge, remembers the wreckage, and builds the crossing that holds.", dataPage: "story", theme: "#050505" },
  { slug: "terms", kind: "page", index: false, indexNote: "HELD — terms are unfinished; do not launch (G11, G15)", title: "Terms and Conditions | IICL", description: "Terms covering use of the IICL website and our services.", dataPage: "terms", theme: "#ffffff" },
  { slug: "sitemap", kind: "page", title: "Sitemap | IICL", description: "Every page on the IICL website, in one list.", dataPage: "sitemap", theme: "#ffffff" },
  { slug: "chillifries", kind: "page", index: false, indexNote: "coming-soon product; Q3 default is to remove unlaunched names", title: "ChilliFries | Coming Soon | IICL", description: "ChilliFries, IICL's newest product, is on the way. Get notified when it launches.", dataPage: "chillifries", theme: "#060606" },
  { slug: "aboutus", kind: "page", title: "About IICL | Enterprise AI and Technology Company", description: "Meet IICL, an enterprise AI and technology company delivering governed AI solutions and specialised technology teams from India and the USA.", dataPage: "aboutus", theme: "#ffffff" },
  { slug: "agentic-ai", kind: "page", title: "Agentic AI Solutions for Enterprise Workflows | IICL", description: "Design, validate and operate governed Agentic AI workflows with controlled tools, human authority, measurable outcomes and enterprise integration.", dataPage: "agentic-ai", theme: "#ffffff" },
  { slug: "ai-genai-services", kind: "page", title: "Enterprise AI Consulting & GenAI Implementation | IICL", description: "Move enterprise AI from discovery and Proof of Value to governed production with IICL's GenAI consulting, integration and implementation services.", dataPage: "ai-genai-services", theme: "#ffffff" },
  { slug: "banking", kind: "page", title: "AI Solutions for Banks and Financial Institutions | IICL", description: "Secure AI automation for banking operations: customer service, document verification, loan processing and collections, with auditable human review.", dataPage: "banking", theme: "#ffffff" },
  { slug: "blog-ivaak-ai", kind: "page", title: "How AI Voice Agents Change Customer Engagement | IICL", description: "Why customer expectations outgrew IVR menus, and how enterprise-grade AI voice agents now handle real conversations end to end.", dataPage: "blog-ivaak-ai", theme: "#ffffff" },
  { slug: "blog-choosing-processes", kind: "page", title: "How to Choose the First Process to Automate | IICL Blog", description: "Most failed AI projects picked the wrong process, not the wrong model. The five tests we run before agreeing to build anything.", dataPage: "blog-choosing-processes", theme: "#ffffff" },
  { slug: "blog-human-in-the-loop", kind: "page", title: "Where a Person Has to Stay in the Loop | IICL Blog", description: "Full autonomy is rarely the goal. How we decide which decisions an AI agent commits, which it drafts for review, and which it never touches.", dataPage: "blog-human-in-the-loop", theme: "#ffffff" },
  { slug: "blog-ai-integration-reality", kind: "page", title: "What AI Integration Actually Involves | IICL Blog", description: "The model is rarely the hard part. What enterprise AI delivery really consists of when an agent has to talk to the systems you already run.", dataPage: "blog-ai-integration-reality", theme: "#ffffff" },
  { slug: "blog-iwac-ai", kind: "page", title: "How to Run Sales and Support on WhatsApp | IICL", description: "How businesses use WhatsApp to capture leads, take orders, collect payments and support customers without adding headcount.", dataPage: "blog-iwac-ai", theme: "#ffffff" },
  { slug: "blog-trufix-ai", kind: "page", title: "AI Ticket Resolution Verification for IT Support | IICL", description: "Why traditional ticketing systems close tickets that were never really fixed, and how AI resolution verification rebuilds trust in IT support.", dataPage: "blog-trufix-ai", theme: "#ffffff" },
  { slug: "blog", kind: "page", title: "AI Insights and Knowledge Centre | IICL Blog", description: "Practical articles on enterprise AI agents, voice automation, WhatsApp commerce and industry AI adoption, written by the IICL delivery team.", dataPage: "blog", theme: "#ffffff" },
  { slug: "brain", kind: "model", title: "IICL — AI Brain 3D Model", component: "Brain", bodyClass: "model-page model-brain", theme: "#050505" },
  { slug: "chatbot", kind: "model", title: "IICL — Chatbot Engine 3D Model", component: "Chatbot", bodyClass: "model-page", theme: "#050505" },
  { slug: "contact-centre", kind: "page", title: "AI Contact Centre and Customer Support Automation | IICL", description: "Automate inbound and outbound contact centre work with AI voice agents, agent assist, intelligent routing and call summarisation, with human handover.", dataPage: "contact-centre", theme: "#ffffff" },
  { slug: "contracts", kind: "page", title: "Contract and Engagement Models | IICL", description: "How IICL contracts for delivery: fixed-scope projects, dedicated pods, flexible teams, contract-to-hire, managed operations and advisory retainers.", dataPage: "contracts", theme: "#ffffff" },
  { slug: "use-cases", kind: "page", title: "AI Use Cases and Deployments | IICL", description: "Complete enterprise AI workflows described end to end: the process, what was built around it, and what the design is meant to improve.", dataPage: "use-cases", theme: "#ffffff" },
  { slug: "gcc-careers", kind: "page", title: "Contract Technology Roles in GCC Teams | IICL", description: "Contract engineering roles inside GCC and enterprise technology teams across AI, data, cloud, security, product engineering and enterprise platforms." , dataPage: "gcc-careers", theme: "#ffffff" },
  { slug: "contactus", kind: "page", title: "Contact IICL | AI Solutions Company in Hyderabad", description: "Talk to IICL about AI agents, voice AI, WhatsApp automation, ERP, application development or staffing. Offices in Hyderabad, India and the USA.", dataPage: "contactus", theme: "#ffffff" },
  { slug: "data-stream", kind: "model", title: "IICL — Global Delivery Stream 3D Model", entry: "data-stream.js", sceneLabel: "Interactive global delivery stream 3D model", bodyClass: "model-page model-stream", theme: "#050505" },
  { slug: "erp-services", kind: "page", title: "ERP Implementation and Integration Services | IICL", description: "ERP consulting, implementation, customisation, migration and support, connecting finance, HR, procurement, inventory and sales in one system.", dataPage: "erp-services", theme: "#ffffff" },
  { slug: "finance", kind: "page", title: "AI and Automation Solutions for Finance Teams | IICL", description: "Automate invoice processing, reconciliation, forecasting and expense review, with human approval, audit logs and access control at every step.", dataPage: "finance", theme: "#ffffff" },
  { slug: "galaxy", kind: "model", title: "IICL — Product Galaxy 3D Model", component: "Galaxy", bodyClass: "model-page model-galaxy", theme: "#050505" },
  { slug: "globe", kind: "model", title: "IICL — Global Network 3D Model", component: "Globe", bodyClass: "model-page model-globe", theme: "#050505" },
  { slug: "gyro-globe", kind: "model", title: "IICL — Gyro Globe 3D Model", component: "GyroGlobe", bodyClass: "model-page model-globe", theme: "#050505" },
  { slug: "gcc-technology-teams", kind: "page", title: "GCC Technology Teams & Niche Tech Hiring in India | IICL", description: "Build and scale GCC technology teams in India across AI, data, cloud, cybersecurity, product engineering and enterprise platforms with IICL.", dataPage: "gcc-technology-teams", theme: "#ffffff" },
  { slug: "healthcare", kind: "page", title: "AI Solutions for Hospitals and Healthcare Providers | IICL", description: "AI and automation for hospitals, clinics and diagnostic centres: appointment booking, call automation, reminders and patient support, with human review.", dataPage: "healthcare", theme: "#ffffff" },
  { slug: "helpdesk", kind: "page", title: "IT Help Desk and Managed Support Services | IICL", description: "Managed IT help desk covering user support, application support, incident management and access requests across phone, email, chat and WhatsApp.", dataPage: "helpdesk", theme: "#ffffff" },
  { slug: "hologram", kind: "model", title: "IICL — AI Brain Hologram 3D Model", entry: "hologram.js", sceneLabel: "Interactive red particle AI brain hologram", bodyClass: "model-page model-brain", theme: "#050505" },
  { slug: "hr", kind: "page", title: "AI Solutions for HR and Recruitment Teams | IICL", description: "AI automation across the employee lifecycle, covering recruitment, onboarding, attendance, engagement and exit, with fairness testing and human approval.", dataPage: "hr", theme: "#ffffff" },
  { slug: "human-brain", kind: "model", title: "IICL — Human Brain 3D Model", component: "HumanBrain", bodyClass: "model-page", theme: "#050505" },
  { slug: "icognito", kind: "page", title: "iCognito.ai | Omnichannel AI Customer Engagement", description: "iCognito handles customer enquiries across channels, drawing on your business systems to answer accurately and escalate to a person when needed.", dataPage: "iCognito", theme: "#ffffff" },
  { slug: "idental", kind: "page", title: "iDental.ai | Dental Practice Management Software India", description: "Run your dental clinic end to end: appointments, patient records, treatment plans, billing and WhatsApp reminders for individual dentists and chains.", dataPage: "idental", theme: "#ffffff" },
  { slug: "index", kind: "home", title: "Enterprise AI & GCC Technology Teams | IICL", description: "Build enterprise AI solutions and specialised GCC technology teams across AI, data, cloud, cybersecurity, platforms and product engineering with IICL.", component: "IICLHero", theme: "#121820" },
  { slug: "ivaak", kind: "page", title: "iVaak.ai | Multilingual AI Voice Agents for Business", description: "Automate inbound and outbound calls with AI voice agents that handle enquiries, bookings, reminders and follow-ups, and transfer to a person with context.", dataPage: "ivaak", theme: "#ffffff" },
  { slug: "iwac", kind: "page", title: "iWac.ai | WhatsApp Commerce & Customer Engagement", description: "iWac is a WhatsApp platform for handling enquiries, taking orders, sending reminders, collecting payments and supporting customers in one conversation.", dataPage: "iwac", theme: "#ffffff" },
  { slug: "legal", kind: "page", title: "AI Solutions for Legal Teams and Law Firms | IICL", description: "AI-assisted contract review, document search, summarisation and obligation tracking for law firms and corporate legal teams. Lawyers review every output.", dataPage: "legal", theme: "#ffffff" },
  { slug: "lexgenie", kind: "page", index: false, indexNote: "product withdrawn from the public roster", title: "LexGenie.ai - AI Contract and Legal Document Assistant", description: "Review, search and manage legal documents with AI: contract summaries, clause extraction, risk flagging and obligation tracking, reviewed by your lawyers.", dataPage: "lexgenie", theme: "#ffffff" },
  { slug: "logistics", kind: "page", title: "AI Solutions for Logistics and Transportation | IICL", description: "AI for logistics operations: shipment tracking, ETA prediction, route planning, POD automation, billing accuracy and exception alerts.", dataPage: "logistics", theme: "#ffffff" },
  { slug: "manufacturing", kind: "page", title: "AI Solutions for Manufacturing Companies | IICL", description: "Reduce downtime and quality escapes with AI for predictive maintenance, visual inspection, demand planning and energy optimisation on the plant floor.", dataPage: "manufacturing", theme: "#ffffff" },
  { slug: "microchip", kind: "model", title: "IICL — AI Microchip 3D Model", component: "Microchip", bodyClass: "model-page model-chip", theme: "#050505" },
  { slug: "neural-network", kind: "model", title: "IICL — AI Neural Network 3D Model", component: "NeuralNetwork", bodyClass: "model-page model-network", theme: "#050505" },
  { slug: "performedge", kind: "page", index: false, indexNote: "product withdrawn from the public roster", title: "PerformEdge.ai - Facial Recognition Attendance System", description: "Smart attendance and workforce management with face recognition, shift and leave handling, overtime tracking, reports and payroll integration.", dataPage: "performedge", theme: "#ffffff" },
  { slug: "privacy-policy", kind: "page", title: "Privacy Policy | Intelligence India.Com Limited", description: "Read how Intelligence India.Com Limited collects, uses, shares, retains and protects personal information submitted through the IICL website.", dataPage: "privacy-policy", theme: "#ffffff" },
  { slug: "quantafin", kind: "page", index: false, indexNote: "product withdrawn from the public roster", title: "QuantaFin.ai - GenAI Financial Analysis and Insights", description: "QuantaFin turns financial data into actionable intelligence, using large language models to answer questions about your numbers in plain language.", dataPage: "quantafin", theme: "#ffffff" },
  { slug: "staff-augmentation", kind: "page", index: false, indexNote: "301 → /gcc-technology-teams (G7, F2)", title: "IT Staff Augmentation Services for GCCs and Enterprises | IICL", description: "Technology staff augmentation for GCCs, enterprises and startups, covering AI/ML, data, cloud, DevOps, Java, .NET, mobile, QA and cybersecurity.", dataPage: "staff-augmentation", theme: "#ffffff" },
  { slug: "supply-chain", kind: "page", title: "AI Supply Chain Planning and Optimisation Solutions | IICL", description: "AI-driven demand forecasting, inventory optimisation, order prioritisation and transport planning, starting from a review of the data you already hold.", dataPage: "supply-chain", theme: "#ffffff" },
  { slug: "thank-you", kind: "page", index: false, indexNote: "post-conversion utility page, no search intent", title: "Thank You | IICL", description: "Your enquiry has reached IICL. Here is what happens next.", dataPage: "thank-you", theme: "#ffffff" },
  { slug: "trufix", kind: "page", title: "TruFix.ai | AI Ticketing & Resolution Verification", description: "TruFix verifies that IT and facilities tickets are genuinely resolved, not just closed, using AI to confirm the fix before the ticket is signed off.", dataPage: "trufix", theme: "#ffffff" },
  { slug: "usecase-ivaak-customercare", kind: "page", title: "AI Voice Agents for Customer Care | iVaak Use Case", description: "How customer care teams use iVaak AI voice agents to handle routine calls, qualify enquiries and hand over to a person with full context.", dataPage: "usecase-ivaak-customercare", theme: "#ffffff" },
  { slug: "usecase-ivaak-healthcare", kind: "page", title: "AI Voice Agents for Patient Communication | iVaak Use Case", description: "How healthcare providers use iVaak AI voice agents for appointment booking, reminders and patient enquiries, with escalation to clinical staff.", dataPage: "usecase-ivaak-healthcare", theme: "#ffffff" },
  { slug: "usecase-ivaak-realestate", kind: "page", title: "AI Voice Agents for Real Estate Enquiries | iVaak Use Case", description: "How real estate teams use iVaak AI voice agents to respond to property enquiries instantly, qualify buyers and schedule site visits.", dataPage: "usecase-ivaak-realestate", theme: "#ffffff" },
  { slug: "voice-agent", kind: "model", title: "IICL — AI Voice Agent 3D Model", entry: "voice-agent.js", sceneLabel: "Interactive AI voice agent waveform 3D model", bodyClass: "model-page model-voice", theme: "#050505" },
  { slug: "voice-frequency", kind: "model", title: "IICL — Voice Frequency 3D Model", component: "VoiceFrequency", bodyClass: "model-page", theme: "#050505" },
  { slug: "web-mobile-dev", kind: "page", title: "Web and Mobile App Development Company | IICL Hyderabad", description: "Custom enterprise portals, mobile apps, SaaS products and customer platforms, built with optional AI features and supported after launch.", dataPage: "web-mobile-dev", theme: "#ffffff" },
  { slug: "whatsapp-business", kind: "page", title: "WhatsApp Business API Integration and Automation | IICL", description: "Connect WhatsApp to your website, CRM, ERP and payment gateway to generate leads, take orders, send updates and automate customer support.", dataPage: "whatsapp-business", theme: "#ffffff" },
];
